# Generated by Django 2.1.2 on 2018-11-17 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_id', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=200)),
                ('user', models.CharField(max_length=30)),
                ('params', models.TextField()),
                ('timestamp', models.CharField(max_length=200)),
            ],
        ),
    ]
